apiVersion: v1  # for service - core/ can be ommited
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  selector:  # here it has directly key: value pairs
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80  # outside world port
      targetPort: 8080  # port exposed or used in the container
    # - protocol: 'TCP'
    #   port: 433
    #   targetPort: 433
  type: LoadBalancer
