apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: partorg/kub-data-demo:3
          env:
            - name: STORY_FOLDER
              # value: 'story'
              valueFrom:
                configMapKeyRef: 
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story  # container internal path where it should be mounted
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
        # - name: story-volume
        #   hostPath:
        #     path: /data  # path on the host machine where data should be stored
        #     type: DirectoryOrCreate
        # - name: story-volume
        #   emptyDir: {}
